In [8]:
import pandas as pd
import numpy as np
import scipy.stats as st
from dash import Dash, dcc, html, Input, Output
import plotly.express as px
import pprint
import json

In [9]:
# Due to mixed data, defining dtype as string
dtype = str
#Reading in the csv's to df's with pandas
measurements_df = pd.read_csv(measurements_path, dtype=dtype)
stations_df = pd.read_csv(stations_path, dtype=dtype)

#Changing the measurements date to proper date. 
measurements_df['msmt_date'] = pd.to_datetime(measurements_df['msmt_date'], errors='coerce')

# Focusing the measurements df to contain the columns we want, and renaming the columns
focused_measurements_df = measurements_df[['site_code', 'msmt_date', 'gwe', 'wlm_qa_desc']]
focused_measurements_df.columns = ['Site Code', 'Measurement Date', 'Groundwater Elevation', 'Quality']

# Repeat for stations
focused_stations_df = stations_df[['site_code', 'latitude', 'longitude']]
focused_stations_df.columns = ['Site Code', 'Latitude', 'Longitude']

# Merge DataFrames on 'Site Code'
df = pd.merge(focused_measurements_df, focused_stations_df, on='Site Code', how='left')
df.dropna(inplace=True)
df

,Site Code,Measurement Date,Groundwater Elevation,Quality,Latitude,Longitude
0,320000N1140000W001,2023-11-30 14:59:00,122.820,Good,36.56048,-121.75463
1,320000N1140000W001,2023-10-26 16:08:00,162.420,Good,36.56048,-121.75463
2,320000N1140000W001,2023-09-28 00:00:00,160.920,Good,36.56048,-121.75463
3,320000N1140000W001,2023-08-31 00:00:00,168.920,Good,36.56048,-121.75463
4,320000N1140000W001,2023-07-27 00:00:00,161.720,Good,36.56048,-121.75463
...,...,...,...,...,...,...
5463556,419980N1215455W001,2008-11-19,4014.010,Good,41.99800,-121.54550
5463557,419980N1215455W001,2008-11-20,4013.959,Good,41.99800,-121.54550
5463558,419980N1215455W001,2008-11-21,4014.035,Good,41.99800,-121.54550
5463559,419980N1215455W001,2008-11-22,4014.009,Good,41.99800,-121.54550
5463560,419980N1215455W001,2008-11-23,4014.026,Good,41.99800,-121.54550

In [13]:
df.to_csv('ca_groundwater_project_data.csv', index=False)